### PR TITLE
More changes to make it compatible with Akka 2.2.1.

### PR DESCRIPTION
**Pull request by melan**
The most common change is switch from Props(new Class(...)) to Props(classOf[Class], ...)

These changes aren't backward compatible so if you want to keep them in separate branch - please let me know I will move them

### CODE REVIEW

**Comment by sstone** [comment]
Hi,
As you guessed I'm going to wait a just bit longer before I merge changes that are not compatible with akka 2.1.X (because all production projects that I work on are using 2.1.X right now). I'm not sure yet that I want to create a new branch for akka 2.2.X.
Thanks!

**Comment by melan** [comment]
Is it possible to create a branch for 2.2.X and I'll move these changes to the branch?

**Comment by sstone** [comment]
Yes, I've created a new branch: scala2.10_akka2.2.

**Comment by mbseid** [comment]
If this could be merged and deployed as well it would be really helpful. I had to compile @melan's branch and assemble it to a jar so that I could use the client. Any plans to merge this in the future?

**Comment by sstone** [comment]
Hi,
This a an old PR and there are now projects using amqp-client with akka 2.2.X and akka 2.3.X. Can you please tell me what you need from this PR that is missing in the regular versions ?
Thanks

**Pull request closed without merging**
