### PR TITLE
Remove temporary watcher as a listener when it is stopped

### PR DESCRIPTION
**Pull request by ljcoomber**
The temporary actor used as a watcher on the channel / connection remains as a status listener, even after it has been stopped. AFAICT this doesn't break anything, but it does mean we see dead lettered messages when a connection or channel closes.

This PR removes the listener when stopping the actor.

### CODE REVIEW

**Comment by sstone** [comment]
Hi,
Good catch! I told myself to fix this (using DeathWatch) a few weeks ago and just forgot. I was thinking of something like (in ChannelOwner.scala):

   case AddStatusListener(actor) => {
      statusListener.map(context.unwatch)
      context.watch(actor)
      statusListener = Some(actor)
      actor ! Connected
    }
    case Terminated(actor) if statusListener == Some(actor) => {
      context.unwatch(actor)
      statusListener = None
    }

WDYT ?
Thanks!

**Comment by ljcoomber** [comment]
Hi, warning: this is my first look at Akka code :-)  

AFAICT, Deathwatch seems the better option as we are relying on Akka built-in functionality for doing Akka housekeeping.

I've amended the PR. I've factored out the commonality for the AddStatusListener flow, and put  the Terminated flow into the unhandled() method, which seems to be the idiomatic thing to do for common handling based on the (limited number of) other FSM implementations I've seen.

There is enough logic now to lift out the status handling into a trait that is shared by ChannelOwner and ConnectionOwner, and am happy to put that in if you agree.

Cheers

**Comment by sstone** [comment]
Ok, it looks good to me. It would be nice to include a unit test too:
- register a listener
- stop the listener
- stop or crash the channel owner (by asking it to check if queue "no_such_queue" exists for example)
- check that you don't receive dead letter messages (to do that you can create a probe actor and subscribe it to the dead letter event stream)
  If you're just starting with Akka and don't have time for this, don't worry I'll merge and add the test myself during the week-end. 

Thanks!

**Comment by ljcoomber** [comment]
Happy to do (and will learn from doing) the test, but it will be early next week before I get on it.

**Comment by ljcoomber** [comment]
@sstone tests done, good for review

**Pull request merged**
