### PR TITLE
Scala2.10

### PR DESCRIPTION
**Pull request by pandeykumar**
1) Fixed issue while connecting to default exchange
2) Refactored github.sstone package name to github/sstone so that unit test can be run from IDE etc.

### CODE REVIEW

**Comment by sstone** [comment]
Hi,

For 2) it works for me (and a few others) with Intellij IDEA, what is your setup ? I don't think that using folders with "." in their names is invalid but it's arguably not a very good practice. 
For 1) I guess that you want to consume from a queue using the automatic binding on the default exchange without declaring your own bindings and it's a use case that I've overlooked... but I'd rather add an option to declare consumers w/o bindings than add explicit support for bindings on "". Do I understand your use case correctly ?

There are a few copy/paste typos in your PR (see RpcServer for example) so I cannot merge as is but I see your points.

As a side note, I think that it would be clearer to have separate commits for bug fixes/enhancement (1) and purely "cosmetic" changes (2) otherwise it's a bit harder to review the PR :-)

Thanks for finding a bug!

Fabrice

**Comment by pandeykumar** [comment]
For 1)  If you define a queue from the rabbitmq admin console,  by default it is bound to the default exchange using the queue name as the key. 

yep messed up the checkin as I'm still learning the ropes on git.Sorry about that.

The typos seems to be introduced by Eclipse refactoring -  I'm using eclipse scala IDE and it just went nuts trying to figure out the imports in refactor.  I fixed anything I could see.
Do I need to initiate new pull?

**Comment by sstone** [comment]
For 1), all queues are bound to their name on the default exchange, that's part of the specs. I am "forcing" users to declare bindinds for their consumers, and you cannot redeclare bindings to the default exchange. I will create a new issue and use your code to fix it, but I'm working on a cleaner way to let users specificy bindings, queues, ...

I won't fix 2) yet 

Can you please submit a new PR for 1) ? If you don't have time I'll work on it over the weekend anyway. 
Thanks!

**Comment by sstone** [comment]
see Issue #17 
I've thought it over and since that the library  is a simple wrapper for the rabbitmq client it should not behave differently and should fail when users attempt to create bindings on the default exchange, so I won't implement 1) after all.
I you're stuck you'll have to declare an additionnal binding. A fix (and I believe a improved message-based implementation) is on its way on branch wip-messages.
Thanks again!

**Pull request closed without merging**
